[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "node index.js"
  port = 2022

[[redirects]]
  from = "/playground"
  to = "/projects/"
  status = 301

[[redirects]]
  from = "/work"
  to = "/work/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about/"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/projects/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301
